version: '3.8'

services:
  airport-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: airport-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword123
      - MSSQL_PID=Express
    volumes:
      - mssql_data:/var/opt/mssql
      - ./databases/airport:/airport  
    user: "root"
    ports:
      - "1433:1433"
    networks:
      - airport-network

  sqlserver-configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./databases/airport:/airport
    depends_on:
      - airport-db
    command: >
      bash -c '
      sleep 60;
      echo "Running SQL scripts";
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -i /airport/delete_database.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -i /airport/create_database.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_main_schema.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_client_schema.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_users.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_airports.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_airplanes.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_flights.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_reservations.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/create_reservation_passengers.sql;
      /opt/mssql-tools18/bin/sqlcmd -C -S airport-db -U sa -P StrongPassword123 -d Airport -i /airport/init.sql;
      echo "SQL scripts executed";
      exit 0;'
    networks:
      - airport-network


  api-airport:
    build:
      context: ./api-airport/api-airport
    container_name: api-airport
    environment:
      ConnectionStrings__DefaultConnection: "Server=airport-db;Database=Airport;User Id=sa;Password=StrongPassword123;TrustServerCertificate=True;"
      JWT__Issuer: "http://api-airport:8081"
      JWT__Audience: "http://localhost:3001"
      GRPCSETTINGS__AuthServiceUrl: "http://sign-service:50051"
      CORS__AllowedOrigins__0: "http://localhost:3001"
    depends_on:
      - airport-db
      - sign-service
    ports:
      - "8081:8080"
    networks:
      - airport-network


  portal:
    build:
      context: ./portal
      args:
        REACT_APP_API_BASE_URL: "http://localhost:8081/api"
        REACT_APP_AUTH_API_BASE_URL: "http://localhost:8080"
    container_name: portal
    ports:
      - "3001:80"
    networks:
      - airport-network

networks:
  airport-network:
    driver: bridge

volumes:
  mssql_data:
