CREATE TABLE main.Airports (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL,  
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL
);
