CREATE TABLE client.Users (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(100) NOT NULL,
    surname NVARCHAR(100) NOT NULL,
    role NVARCHAR(100) NOT NULL,
    email NVARCHAR(256) NOT NULL UNIQUE,
    passwordhash NVARCHAR(MAX) NOT NULL
);
